### PR TITLE
Use AWS_USERNAME to set the role-session-name

### PR DESCRIPTION
**Pull request by matthew-intercom**
Currently the role-session-name is being defined as a date. This means that in Cloudtrail, API actions done via assume-role show up as a timestamp.

However when you assume-role via the AWS Console, AWS sets role-session-name to be the username of the person who initially logged in.

This changes assume-role to use the AWS_USERNAME field to closer match how AWS does it.

### CODE REVIEW

**Comment by matthew-intercom** [comment]
This is an example of how AWS handles the username currently.

image

**Comment by gabrielkoo** [comment]
+1 for this, since the role session name is very important when we would like to identify the assume role user in CloudTrail Logs.

**Comment by tanasegabriel** [comment]
+1 for this! The only way of identifying the user name through `assume-role` is hunting down the temporary Access Key ID in the child account and comparing it against the `AssumeRole` event in the parent account. This PR would make things so much easier.

**Review by grahamjenson — APPROVED** [review]

**Comment by heimdall-asguard** [comment]
Review Error for grahamjenson @ 2019-10-22 20:09:13 UTC
User cannot review their own commit

**Review by itstehkman — APPROVED** [review]

**Comment by grahamjenson** [comment]
Cheers for this awesome PR, sorry it took so long to get to it.

**Comment by matthew-intercom** [comment]
No worries. Thanks for approving!

**Pull request merged**
