### PR TITLE
JSON must be quoted to prevent leading zeroes from being dropped as int

### PR DESCRIPTION
**Pull request by mhumeSF**
Small update, but I think will help.

### CODE REVIEW

**Review by krobertson — APPROVED** [review]

**Comment by krobertson** [comment]
doh, my +1 isn't good enough for Heimdall :)

**Comment by grahamjenson** [comment]
+1

**Comment by grahamjenson** [comment]
+1

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
grahamjenson | 1 | +1 

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/assume-role&ref=89f62872f60839a5af046dd27acbfec5c66d533b)

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1 | Message
------------ | ------------- | ----------
grahamjenson | 1 | +1 

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/assume-role&ref=f99a9cce3925633884809b8f0bebf4205e6efaa8)

**Pull request merged**
