### PR TITLE
After script hook

### PR DESCRIPTION
**Pull request by brainstorm**
We continue to use your great script in our organization and would like to include a crude hooks functionality that, in our opinion, improves the UX of our developers when using `assume-role`.

Hope it works for you too :)

/cc @reisingerf

PD: Thanks for the CI addition, btw! ;)

### CODE REVIEW

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1 | Message
------------ | ------------- | ----------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/assume-role&ref=98689f6d23934c3855087adc3db77f84bf446930)

**Comment by grahamjenson** [comment]
I don't think this is the correct approach, I think the better idea would be to build a tool that uses assume-role and composes it with a script e.g. `valut_assume.bash`

```
#!/bin/bash
set -e
assume-role account user
vaule login...
```

**Comment by reisingerf** [comment]
Hi Graham,

thanks for the quick feedback!
Your suggestion was indeed our initial approach, however we did not get it to work... 

Could you help us get this to work or perhaps even give us a working example?
We basically want to wrap assume-role, with some calls to vault and export additional env vars to the current shell.

I can wrap the assume-role script as you mentioned, but then the env variables are not available in my shell (as they are exported in the sub-shell of my wrapper). Same is true for the vars I export in my wrapper script (even though I source the wrapper script following your assume-role example).

Thanks a lot for your support!

**Comment by grahamjenson** [comment]
If you want to call a script that exports to the local context you can use `.  ./script` if `script` was like

```
#!/bin/bash

assume-role jenson sudo
vault login...
```

from https://stackoverflow.com/questions/496702/can-a-shell-script-set-environment-variables-of-the-calling-shell

**Comment by reisingerf** [comment]
I guess I was looking for way to avoid the `.` notation, but I can just set up an alias for aesthetics.
Thanks for all you help!

**Comment by grahamjenson** [comment]
@reisingerf So the way assume-role actually works is by defining a function that you call, functions are executed in the same bash process. The problem is that you have to source them into your bash.rc for them to be easily usable.

So to customize your script you could write a script 

```
#!/bin/bash

assume-role-with-vault() {
 assume-role $1 $2 $3
 vault login
}
```

then have your developers source that into their bash.rc profiles.

**Comment by reisingerf** [comment]
Thanks!

This is great and the combination of your and our script makes our daily work a lot easier!

On 22 May 2018, at 02:54, Graham Jenson <notifications@github.com<mailto:notifications@github.com>> wrote:


@reisingerf<https://github.com/reisingerf> So the way assume-role actually works is by defining a function that you call, functions are executed in the same bash process. The problem is that you have to source them into your bash.rc for them to be easily usable.

So to customize your script you could write a script

#!/bin/bash

assume-role-with-vault() {
 assume-role $1 $2 $3
 vault login
}


then have your developers source that into their bash.rc profiles.

**Pull request closed without merging**
